# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: complex.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='complex.proto',
  package='example.complex',
  syntax='proto3',
  serialized_pb=_b('\n\rcomplex.proto\x12\x0f\x65xample.complex\"!\n\x05\x44ummy\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\"f\n\x07\x43omplex\x12)\n\tone_dummy\x18\x01 \x01(\x0b\x32\x16.example.complex.Dummy\x12\x30\n\x10multiple_dummies\x18\x02 \x03(\x0b\x32\x16.example.complex.Dummyb\x06proto3')
)




_DUMMY = _descriptor.Descriptor(
  name='Dummy',
  full_name='example.complex.Dummy',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='example.complex.Dummy.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='example.complex.Dummy.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=67,
)


_COMPLEX = _descriptor.Descriptor(
  name='Complex',
  full_name='example.complex.Complex',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='one_dummy', full_name='example.complex.Complex.one_dummy', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='multiple_dummies', full_name='example.complex.Complex.multiple_dummies', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=171,
)

_COMPLEX.fields_by_name['one_dummy'].message_type = _DUMMY
_COMPLEX.fields_by_name['multiple_dummies'].message_type = _DUMMY
DESCRIPTOR.message_types_by_name['Dummy'] = _DUMMY
DESCRIPTOR.message_types_by_name['Complex'] = _COMPLEX
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Dummy = _reflection.GeneratedProtocolMessageType('Dummy', (_message.Message,), dict(
  DESCRIPTOR = _DUMMY,
  __module__ = 'complex_pb2'
  # @@protoc_insertion_point(class_scope:example.complex.Dummy)
  ))
_sym_db.RegisterMessage(Dummy)

Complex = _reflection.GeneratedProtocolMessageType('Complex', (_message.Message,), dict(
  DESCRIPTOR = _COMPLEX,
  __module__ = 'complex_pb2'
  # @@protoc_insertion_point(class_scope:example.complex.Complex)
  ))
_sym_db.RegisterMessage(Complex)


# @@protoc_insertion_point(module_scope)
