# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: enumeration.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='enumeration.proto',
  package='example.enumerations',
  syntax='proto3',
  serialized_pb=_b('\n\x11\x65numeration.proto\x12\x14\x65xample.enumerations\"@\n\x0b\x45numeration\x12\x31\n\teye_color\x18\x01 \x01(\x0e\x32\x1e.example.enumerations.EyeColor*x\n\x08\x45yeColor\x12\x19\n\x15\x45YE_COLOR_UNSPECIFIED\x10\x00\x12\x13\n\x0f\x45YE_COLOR_GREEN\x10\x01\x12\x12\n\x0e\x45YE_COLOR_BLUE\x10\x02\x12\x14\n\x10\x45YE_COLOR_YELLOW\x10\x03\x12\x12\n\x0e\x45YE_COLOR_GRAY\x10\x04\x62\x06proto3')
)

_EYECOLOR = _descriptor.EnumDescriptor(
  name='EyeColor',
  full_name='example.enumerations.EyeColor',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='EYE_COLOR_UNSPECIFIED', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EYE_COLOR_GREEN', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EYE_COLOR_BLUE', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EYE_COLOR_YELLOW', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EYE_COLOR_GRAY', index=4, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=109,
  serialized_end=229,
)
_sym_db.RegisterEnumDescriptor(_EYECOLOR)

EyeColor = enum_type_wrapper.EnumTypeWrapper(_EYECOLOR)
EYE_COLOR_UNSPECIFIED = 0
EYE_COLOR_GREEN = 1
EYE_COLOR_BLUE = 2
EYE_COLOR_YELLOW = 3
EYE_COLOR_GRAY = 4



_ENUMERATION = _descriptor.Descriptor(
  name='Enumeration',
  full_name='example.enumerations.Enumeration',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='eye_color', full_name='example.enumerations.Enumeration.eye_color', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=107,
)

_ENUMERATION.fields_by_name['eye_color'].enum_type = _EYECOLOR
DESCRIPTOR.message_types_by_name['Enumeration'] = _ENUMERATION
DESCRIPTOR.enum_types_by_name['EyeColor'] = _EYECOLOR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Enumeration = _reflection.GeneratedProtocolMessageType('Enumeration', (_message.Message,), dict(
  DESCRIPTOR = _ENUMERATION,
  __module__ = 'enumeration_pb2'
  # @@protoc_insertion_point(class_scope:example.enumerations.Enumeration)
  ))
_sym_db.RegisterMessage(Enumeration)


# @@protoc_insertion_point(module_scope)
